baseURL = "https://shanaka-desoysa.github.io/"
languageCode = "en-us"
title = "Shanaka C. DeSoysa"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["taxonomy", "taxonomyTerm"]
uglyURLs = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["RSS"]
