baseURL = "https://blog.geni.ai/notes/"
languageCode = "en-us"
title = "Shanaka C. DeSoysa"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["taxonomy", "taxonomyTerm"]
uglyURLs = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["RSS"]

[markup.goldmark.renderer]
  unsafe= true

[params]
  date_format = "Jan 02, 2006"